accounts/urls.py
from django.contrib.auth import views
from django.conf.urls import url
from django.urls import path
from .views import SignUpView, user_register, get_num

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('registration/', SignUpView.as_view(), name='register'),
    path('registration/', user_register, name='register'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

mynewssite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url
from .views import ViewNews, CreateNews, HomeNews, NewsByCategory, test

urlpatterns = [
    url(r'^$', HomeNews.as_view(), name='index'),
    url(r'^category/(?P<category_id>\d+)$', NewsByCategory.as_view(), name='category'),
    url(r'^news/(?P<pk>\d+)$', ViewNews.as_view(), name='view_news'),
    url(r'^news/add-news/$', CreateNews.as_view(), name='add_news'),
    url(r'news/test/', test, name='test'),

]

accounts/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.urls import reverse


class News(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название новости')
    content = models.TextField(blank=True, verbose_name='Контент')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото', blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано?')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')
    views = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('view_news', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-created_at']


class Category(models.Model):
    title = models.CharField(max_length=150, db_index=True, verbose_name='Название категории')

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_id': self.pk})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['title']

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Это необходимое поле')
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={
                'autocomplete': 'off',
            }),
        }

news/forms.py
from django import forms
from .models import News
import re
from django.core.exceptions import ValidationError


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = [
            'title',
            'content',
            'is_published',
            'category'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'category': forms.Select(attrs={'class': 'form-control'})
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if re.match(r'\d', title):
            raise ValidationError('Название не должно начинаться с цифры')
        return title


class ContactForm(forms.Form):
    subject = forms.CharField(label='Тема письма', widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label='Tекст', widget=forms.Textarea(attrs={'class': 'form-control'}))

accounts/views.py
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from .forms import RegisterForm
from django.http import JsonResponse
import random
import json
from django.contrib.auth.models import User


class SignUpView(generic.CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy('login')
    template_name = 'registration/registration.html'


def user_register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()
            user.save()

        else:
            if User.objects.filter(username=request.POST['user']).exists():
                response = {
                    'message': True
                }
            else:
                response = {
                    'message': False
                }
            return JsonResponse(response)

    else:
        form = RegisterForm()
    return render(request, 'registration/registration.html', {'form': form})


def get_num(request):
    response = {
        'message': 123
    }
    return JsonResponse(response)

news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import NewsForm, ContactForm
from .models import News, Category
from django.views.generic import ListView, DetailView, CreateView
from django.core.mail import send_mail


class HomeNews(ListView):
    model = News
    template_name = 'news/home_news_list.html'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        return context

    def get_queryset(self):
        return News.objects.filter(is_published=True).select_related('category')


class CreateNews(LoginRequiredMixin, CreateView):
    form_class = NewsForm
    template_name = 'news/add_news.html'


class NewsByCategory(ListView):
    model = News
    template_name = 'news/home_news_list.html'
    allow_empty = False
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.objects.get(pk=self.kwargs['category_id'])
        return context

    def get_queryset(self):
        return News.objects.filter(category_id=self.kwargs['category_id'], is_published=True).select_related('category')


class ViewNews(DetailView):
    model = News


def test(requets):
    if requets.method == 'POST':
        form = ContactForm(requets.POST)
        if form.is_valid():
            mail = send_mail(form.cleaned_data['subject'], form.cleaned_data['content'], 'django.test666@gmail.com',
                             ['rotmir.klimov@mail.ru'], fail_silently=True)
            if mail:
                messages.success(requets, 'Письмо успешно отправлено')
                return redirect('test')
            else:
                messages.error(requets, 'Ошибка отправки')
    else:
        form = ContactForm()
    return render(requets, 'news/test.html', {'form': form})

# def add_news(request):
#     if request.method == 'POST':
#         form = NewsForm(request.POST)
#         if form.is_valid():
#             # news = News.objects.create(**form.cleaned_data)
#             news = form.save()
#             return redirect(news)
#     else:
#         form = NewsForm()
#
#     return render(request, 'news/add_news.html', {'form': form})

news/templates/news/add_news.html
{% extends 'news/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Добавить новость
{% endblock %}
{% block sidebar %}

    {% include 'inc/_sidebar.html' %}

{% endblock %}
{% block content %}
    <h1>Добавление новости</h1>
    <form action="{% url 'add_news' %}" method="post">
        {% csrf_token %}

        {{ form.as_p }}


        <button type="submit" class="btn btn-primary btn-block">Добавить новость</button>
    </form>
{% endblock %}

news/templates/news/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'inc/_inc.html' %}
<div class="container mt-3">
    <h1>{% block header %}{% endblock %}</h1>
    <div class="row">
        <div class="col-md-3">
            {% block sidebar %}
            {% endblock %}
        </div>
        <div class="col-md-9">
            {% if messages %}

                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="alert {{ message.tags }}" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}

                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
            {% if page_obj.has_other_pages %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item active">
                            <a class="page-link " href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% endif %}
                    {% for p in page_obj.paginator.page_range %}

                        {% if page_obj.number == p %}
                            <li class="page-item active">
                                <a class="page-link " href="?page={{ p }}">{{ p }}</a>
                            </li>
                        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                            </li>

                        {% endif %}


                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item active">
                            <a class="page-link " href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>

    </div>
</div>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

</body>
</html>

news/templates/news/category.html
{% extends 'news/base.html' %}
{% block title %}
    {{ category }}
{% endblock %}
{% block sidebar %}
    {% include 'inc/_sidebar.html' %}

{% endblock %}
{% block content %}
    {% for item in news %}
        <div class="card mb-3">
            <div class="card-header">
                Категория: <a href="{{ item.category.get_absolute_url }}">{{ item.category.title }}</a>
            </div>
            <div class="card-body">
                <div class="media">
                    {% if item.photo %}
                        <img src="{{ item.photo.url }}" alt="" width="350" class="" height="235">
                    {% else %}
                        <img src="https://picsum.photos/id/237/350/235" alt="" class="">
                    {% endif %}
                    <div class="media-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <p class="card-text">{{ item.content|truncatewords:50 }}</p>
                        <a href="{{ item.get_absolute_url }}" class="btn btn-primary">Read moore</a>
                    </div>
                </div>

            </div>
            <div class="card-footer text-muted">
                {{ item.created_at|date:'Y:m:d H:i' }}
            </div>
        </div>
    {% endfor %}


{% endblock %}

news/templates/news/home_news_list.html
{% extends 'news/base.html' %}
{% block header %}
    {{ title }}
{% endblock %}
{% block title %}
    {{ title }}
{% endblock %}
{% block sidebar %}

    {% include 'inc/_sidebar.html' %}

{% endblock %}
{% block content %}

    {% for item in news_list %}
        <div class="card mb-3">
            <div class="card-header">
                Категория: <a href="{{ item.category.get_absolute_url }}">{{ item.category.title }}</a>
            </div>
            <div class="card-body">
                <div class="media">
                    {% if item.photo %}
                        <img src="{{ item.photo.url }}" alt="" width="350" class="" height="235">
                    {% else %}
                        <img src="https://picsum.photos/id/237/350/235" alt="" class="">
                    {% endif %}
                    <div class="media-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <p class="card-text">{{ item.content|truncatewords:50 }}</p>
                        <a href="{{ item.get_absolute_url }}" class="btn btn-primary">Read moore</a>
                    </div>
                </div>

            </div>
            <div class="card-footer text-muted">
                {{ item.created_at|date:'Y:m:d H:i' }}
            </div>
        </div>
    {% endfor %}

{% endblock %}

news/templates/news/index.html
{% extends 'news/base.html' %}
{% block header %}
    {{ title }}
{% endblock %}
{% block title %}
    {{ title }}
{% endblock %}
{% block sidebar %}

    {% include 'inc/_sidebar.html' %}

{% endblock %}
{% block content %}

    {% for item in news %}
        <div class="card mb-3">
            <div class="card-header">
                Категория: <a href="{{ item.category.get_absolute_url }}">{{ item.category.title }}</a>
            </div>
            <div class="card-body">
                <div class="media">
                    {% if item.photo %}
                        <img src="{{ item.photo.url }}" alt="" width="350" class="" height="235">
                    {% else %}
                        <img src="https://picsum.photos/id/237/350/235" alt="" class="">
                    {% endif %}
                    <div class="media-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <p class="card-text">{{ item.content|truncatewords:50 }}</p>
                        <a href="{{ item.get_absolute_url }}" class="btn btn-primary">Read moore</a>
                    </div>
                </div>

            </div>
            <div class="card-footer text-muted">
                {{ item.created_at|date:'Y:m:d H:i' }}
            </div>
        </div>
    {% endfor %}

{% endblock %}

news/templates/news/list_categories.html
<div class="list-group">

    {% for category in categories %}
        <a href="{{ category.get_absolute_url }}"
           class="list-group-item list-group-item-action">{{ category.title }} <span
                class="badge badge-success badge-pill"><span class="text-success"> {{ category.cnt }}</span></span></a>

    {% endfor %}
</div>

news/templates/news/news_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">{% csrf_token %}
    Удалить {{ object }}
    <button type="submit">
        Удалить
    </button>
</form>


</body>
</html>

news/templates/news/news_detail.html
{% extends 'news/base.html' %}

{% block title %}
    {{ news.title }}
{% endblock %}
{% block sidebar %}

    {% include 'inc/_sidebar.html' %}

{% endblock %}
{% block content %}


    <div class="card mb-3">
        <div class="card-header">
            Категория: <a href="{{  news.category.get_absolute_url }}">{{ news.category }}</a>
        </div>
        <div class="card-body">

                {% if news.photo %}
                    <img src="{{ news.photo.url }}" alt="" width="350" class="float-left mr-3" height="235">
                {% else %}
                    <img src="https://picsum.photos/id/237/350/235" alt="" class="float-left mr-3">
                {% endif %}
                <div class="media-body">
                    <h5 class="card-title">{{ news.title }}</h5>
                    <p class="card-text">{{ news.content }}</p>
                </div>



        </div>
        <div class="card-footer text-muted">
            {{ news.created_at|date:'Y:m:d H:i' }}
        </div>
    </div>


{% endblock %}

news/templates/news/test.html
{% extends 'news/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Отпавить письмо
{% endblock %}
{% block sidebar %}

    {% include 'inc/_sidebar.html' %}

{% endblock %}
{% block content %}
    <h1>Отправка письма</h1>

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-primary btn-block">Отправить</button>
    </form>
{% endblock %}

news/templates/news/views_news.html
{% extends 'news/base.html' %}

{% block title %}
    {{ news.title }}
{% endblock %}
{% block sidebar %}

    {% include 'inc/_sidebar.html' %}

{% endblock %}
{% block content %}


    <div class="card mb-3">
        <div class="card-header">
            Категория: <a href="{{ item.category.get_absolute_url }}">{{ news.category }}</a>
        </div>
        <div class="card-body">

                {% if news.photo %}
                    <img src="{{ news.photo.url }}" alt="" width="350" class="float-left mr-3" height="235">
                {% else %}
                    <img src="https://picsum.photos/id/237/350/235" alt="" class="float-left mr-3">
                {% endif %}
                <div class="media-body">
                    <h5 class="card-title">{{ news.title }}</h5>
                    <p class="card-text">{{ news.content }}</p>
                </div>



        </div>
        <div class="card-footer text-muted">
            {{ news.created_at|date:'Y:m:d H:i' }}
        </div>
    </div>


{% endblock %}

templates/inc/_inc.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Главная</a>
                </li>
                {% if request.user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_news' %}">Добавить новость</a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/"><span class="text-danger">Привет {{ user.username }}</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'password_change' %}"><span class="text-danger">Изменить пароль?</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}"><span class="text-danger">Выйти?</span></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'login' %}"><span class="text-danger">Войти</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}"><span class="text-danger">Регистрация</span></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/inc/_sidebar.html
{% load news_tags %}
{% show_categories %}